CREATE TABLE chefs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name_ar VARCHAR(100) NOT NULL,
    full_name_fr VARCHAR(100),
    position VARCHAR(100),
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);